"""empty message

Revision ID: 0d52f8fa93fa
Revises: b37aa445516d
Create Date: 2020-12-19 23:00:37.194312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d52f8fa93fa'
down_revision = 'b37aa445516d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_image_link', sa.String(length=120), nullable=True))
    op.add_column('shows', sa.Column('artist_name', sa.String(), nullable=False))
    op.add_column('shows', sa.Column('venue_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'venue_name')
    op.drop_column('shows', 'artist_name')
    op.drop_column('shows', 'artist_image_link')
    # ### end Alembic commands ###
