"""empty message

Revision ID: 6a4cc9288592
Revises: 17b0ebf263a3
Create Date: 2020-12-19 10:19:12.408666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4cc9288592'
down_revision = '17b0ebf263a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('cityname', sa.String(length=120), nullable=False))
    op.drop_column('cities', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('cities', 'cityname')
    # ### end Alembic commands ###
