"""empty message

Revision ID: b19c8e375353
Revises: 07ac40a63788
Create Date: 2020-12-22 20:19:14.646144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19c8e375353'
down_revision = '07ac40a63788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('shows', 'show_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###
