"""empty message

Revision ID: c10c1e13be2a
Revises: bc36641f8eb3
Create Date: 2020-12-20 10:49:11.912968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10c1e13be2a'
down_revision = 'bc36641f8eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venues', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'upcoming_shows_count')
    op.drop_column('venues', 'upcoming_shows')
    op.drop_column('venues', 'past_shows_count')
    op.drop_column('venues', 'past_shows')
    # ### end Alembic commands ###
